create table feedback (
  id bigint generated by default as identity,
  author varchar(255) not null,
  conference varchar(255) not null,
  talk varchar(255),
  comment varchar(255),
  rating int,
  primary key (id)
  );
create sequence hibernate_sequence;
